dist: xenial
addons:
  apt:
    sources:
      - key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
        sourceline: 'deb [arch=amd64] http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
    packages:
      # General stuff
      - build-essential
      - cmake
      - pkg-config
      - libhwloc-dev
      - zlib1g-dev
      # OpenCL-related utils
      - ocl-icd-libopencl1
      - ocl-icd-dev
      - ocl-icd-opencl-dev
      - clinfo
      # LLVM-related stuff
      - clang-8
      - libclang-8-dev
      - llvm-8
      - llvm-8-dev

language: rust

branches:
  only:
    - master
    # Github release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/

rust:
  - 1.34.0

env:
  global:
    - POCL_VER=1.3

cache:
  cargo: true
  directories:
    - $HOME/.local

before_install:
  # Build `pocl` distribution if necessary.
  - |
    if [[ ! -x "~/.local/pocl-$POCL_VER/build/bin/poclcc" ]]; then
      mkdir -p ~/.local && cd ~/.local
      curl -sSL "https://github.com/pocl/pocl/archive/v$POCL_VER.tar.gz" > pocl-$POCL_VER.tar.gz
      tar xf "pocl-$POCL_VER.tar.gz"
      cd pocl-$POCL_VER
      mkdir -p build && cd build
      cmake -DWITH_LLVM_CONFIG=/usr/bin/llvm-config-8 -DCMAKE_INSTALL_PREFIX=/usr ..
      make
      cd $TRAVIS_BUILD_DIR
    fi
  - (cd ~/.local/pocl-$POCL_VER/build && sudo make install)
  - clinfo
install:
  - rustup component add rustfmt
  - rustfmt -V
  - rustup component add clippy
  - cargo clippy --version

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --tests --examples --benches -- -D warnings
  - cargo test
